# Generated by Django 3.1.11 on 2021-06-08 11:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='comments',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewuser',
            name='username',
            field=models.CharField(help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
